- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: "{{ 3600*24 }}"

- name: install requirements
  apt: name={{ item }} state=present
  with_items:
      - zlib1g-dev
      - uuid-dev
      - libmnl-dev
      - gcc
      - make
      - git
      - autoconf
      - autoconf-archive
      - autogen
      - automake
      - pkg-config
      - curl